# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/codes/cppgredbook

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/codes/cppgredbook

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/codes/cppgredbook/CMakeFiles /mnt/d/codes/cppgredbook/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/codes/cppgredbook/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named grpc_server

# Build rule for target.
grpc_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpc_server
.PHONY : grpc_server

# fast build rule for target.
grpc_server/fast:
	$(MAKE) -f CMakeFiles/grpc_server.dir/build.make CMakeFiles/grpc_server.dir/build
.PHONY : grpc_server/fast

#=============================================================================
# Target rules for targets named protogen

# Build rule for target.
protogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 protogen
.PHONY : protogen

# fast build rule for target.
protogen/fast:
	$(MAKE) -f CMakeFiles/protogen.dir/build.make CMakeFiles/protogen.dir/build
.PHONY : protogen/fast

greeter-server.o: greeter-server.cpp.o

.PHONY : greeter-server.o

# target to build an object file
greeter-server.cpp.o:
	$(MAKE) -f CMakeFiles/grpc_server.dir/build.make CMakeFiles/grpc_server.dir/greeter-server.cpp.o
.PHONY : greeter-server.cpp.o

greeter-server.i: greeter-server.cpp.i

.PHONY : greeter-server.i

# target to preprocess a source file
greeter-server.cpp.i:
	$(MAKE) -f CMakeFiles/grpc_server.dir/build.make CMakeFiles/grpc_server.dir/greeter-server.cpp.i
.PHONY : greeter-server.cpp.i

greeter-server.s: greeter-server.cpp.s

.PHONY : greeter-server.s

# target to generate assembly for a file
greeter-server.cpp.s:
	$(MAKE) -f CMakeFiles/grpc_server.dir/build.make CMakeFiles/grpc_server.dir/greeter-server.cpp.s
.PHONY : greeter-server.cpp.s

grpc/hello.grpc.pb.o: grpc/hello.grpc.pb.cc.o

.PHONY : grpc/hello.grpc.pb.o

# target to build an object file
grpc/hello.grpc.pb.cc.o:
	$(MAKE) -f CMakeFiles/protogen.dir/build.make CMakeFiles/protogen.dir/grpc/hello.grpc.pb.cc.o
.PHONY : grpc/hello.grpc.pb.cc.o

grpc/hello.grpc.pb.i: grpc/hello.grpc.pb.cc.i

.PHONY : grpc/hello.grpc.pb.i

# target to preprocess a source file
grpc/hello.grpc.pb.cc.i:
	$(MAKE) -f CMakeFiles/protogen.dir/build.make CMakeFiles/protogen.dir/grpc/hello.grpc.pb.cc.i
.PHONY : grpc/hello.grpc.pb.cc.i

grpc/hello.grpc.pb.s: grpc/hello.grpc.pb.cc.s

.PHONY : grpc/hello.grpc.pb.s

# target to generate assembly for a file
grpc/hello.grpc.pb.cc.s:
	$(MAKE) -f CMakeFiles/protogen.dir/build.make CMakeFiles/protogen.dir/grpc/hello.grpc.pb.cc.s
.PHONY : grpc/hello.grpc.pb.cc.s

grpc/hello.pb.o: grpc/hello.pb.cc.o

.PHONY : grpc/hello.pb.o

# target to build an object file
grpc/hello.pb.cc.o:
	$(MAKE) -f CMakeFiles/protogen.dir/build.make CMakeFiles/protogen.dir/grpc/hello.pb.cc.o
.PHONY : grpc/hello.pb.cc.o

grpc/hello.pb.i: grpc/hello.pb.cc.i

.PHONY : grpc/hello.pb.i

# target to preprocess a source file
grpc/hello.pb.cc.i:
	$(MAKE) -f CMakeFiles/protogen.dir/build.make CMakeFiles/protogen.dir/grpc/hello.pb.cc.i
.PHONY : grpc/hello.pb.cc.i

grpc/hello.pb.s: grpc/hello.pb.cc.s

.PHONY : grpc/hello.pb.s

# target to generate assembly for a file
grpc/hello.pb.cc.s:
	$(MAKE) -f CMakeFiles/protogen.dir/build.make CMakeFiles/protogen.dir/grpc/hello.pb.cc.s
.PHONY : grpc/hello.pb.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... grpc_server"
	@echo "... protogen"
	@echo "... greeter-server.o"
	@echo "... greeter-server.i"
	@echo "... greeter-server.s"
	@echo "... grpc/hello.grpc.pb.o"
	@echo "... grpc/hello.grpc.pb.i"
	@echo "... grpc/hello.grpc.pb.s"
	@echo "... grpc/hello.pb.o"
	@echo "... grpc/hello.pb.i"
	@echo "... grpc/hello.pb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

